<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="OrderEntry.aspx.cs" Inherits="SeniorProjectWebsite.OrderEntry.OrderEntry" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="col-md-4">
        <div id="ctlOrder" runat="server" visible="false">
            <asp:HiddenField id="hforderid" runat="server" Value="-1"/>
            <table>
<tbody>
<tr>
<td>Customer : <asp:TextBox ID="txtCustomer" runat="server"></asp:TextBox></td>
</tr>
<tr>
<td>Address : <asp:textbox ID="txtAddress" runat="server"></asp:textbox></td>
</tr>
<tr>
<td>Price : <asp:Label ID="lblPrice" runat="server"></asp:Label></td>
</tr>
<tr>
<td>Delivered : <asp:CheckBox id="chkDelivered" runat="server"/></td>
</tr>
<tr>
<td>Tracking Number : <asp:TextBox ID="txtTrackNum" runat="server"></asp:TextBox></td>
</tr>
<tr>
<td>               <table>
    <tr>
        <td>
            Item : <asp:DropDownList ID="ddlItem" AutoPostBack="true" runat="server"></asp:DropDownList>
        </td>
        <td>
            Quantity : <asp:TextBox ID="txtQuantity" runat="server"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td colspan="2"><asp:GridView ID="grdOrderItems" runat="server" DataKeyNames="OrderProductId" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" OnSelectedIndexChanged="grdOrderItems_SelectedIndexChanged"></asp:GridView></td>
    </tr>
    <asp:Button id="Button1" runat="server" Text="AddItem" OnClick="btnSave1_Click"/>
</table>
</td>
</tr>
<tr>
<td>                <asp:Button runat="server" text="Save Order" id="btnSave" OnClick="btnSave_Click"/>
     
</td>
</tr>
 
 
</tbody>
</table>
               
        </div>
        <asp:Button ID="newOrder" Text="new order" runat="server" onclick="newOrder_Click"/>
        <asp:GridView id="orders" runat="server" OnSelectedIndexChanged="orders_SelectedIndexChanged" AutoGenerateSelectButton="true" DataKeyNames="orderid">
        </asp:GridView>
    </div>
</asp:Content>
