<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="OrderEntry.aspx.cs" Inherits="SeniorProjectWebsite.OrderEntry.OrderEntry" %>
<%@ Register Src="~/OrderEntry/OrderItem.ascx" TagPrefix="uc1" TagName="OrderItem" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="col-md-4">
        <div id="ctlOrder" runat="server" visible="false">
            <table>
<tbody>
<tr>
<td>Customer : <asp:TextBox ID="txtCustomer" runat="server"></asp:TextBox></td>
</tr>
<tr>
<td>Address : <asp:textbox ID="txtAddress" runat="server"></asp:textbox></td>
</tr>
<tr>
<td>Price : <asp:Label ID="lblPrice" runat="server"></asp:Label></td>
</tr>
<tr>
<td>Delivered : <asp:CheckBox id="chkDelivered" runat="server"/></td>
</tr>
<tr>
<td>Tracking Number : <asp:TextBox ID="txtTrackNum" runat="server"></asp:TextBox></td>
</tr>
<tr>
<td>                <uc1:OrderItem id="ordItem" runat="server"/>
</td>
</tr>
</tbody>
</table>
                <asp:GridView ID="grdOrderItems" runat="server" DataKeyNames="orderid" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" OnSelectedIndexChanged="grdOrderItems_SelectedIndexChanged"></asp:GridView>
        </div>
        <asp:Button ID="newOrder" runat="server" />
        <asp:GridView id="orders" runat="server">
        </asp:GridView>
    </div>
</asp:Content>
